### ISSUE TITLE
Error while exporting Slices on a Druid datasource

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/superset#1546]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/caravel-0.12.0-py2.7.egg/caravel/views.py", line 907, in download_dashboards
    models.Dashboard.export_dashboards(ids),
  File "/usr/local/lib/python2.7/dist-packages/caravel-0.12.0-py2.7.egg/caravel/models.py", line 577, in export_dashboards
    database_name=slc.datasource.database.database_name,
AttributeError: 'DruidCluster' object has no attribute 'database_name'
```

**Comment by nishantmonu51** [comment]
@bkyryliuk: can you link the related PR in which this has been fixed ?

**Comment by orendain** [comment]
@bkyryliuk @mistercrunch: Any followup available?  Was this issue addressed?

**Comment by dhananjaymehta** [comment]
Still facing this issue. @mistercrunch any proposed work around for this?
