### ISSUE TITLE
Issue with data labels Distribution Bar Chart when stacked

### ISSUE THREAD

**Issue by ramugr8** [airbnb/superset#2749]
Hi All,

When we are working with Distribution Bar chart, we are able to show data labels when multiple bar, but when we are going to show stacked bar then we are unable to show data labels. Attached the screenshot for your review.

Could you please help us.

### Superset v
![issue](https://cloud.githubusercontent.com/assets/20371395/25937992/6b320552-364b-11e7-8fc0-058d446e3ed7.JPG)
![issue1](https://cloud.githubusercontent.com/assets/20371395/25938002/72b8c694-364b-11e7-9a66-942f9f125396.JPG)

ersion

**Comment by mistercrunch** [comment]
An easy fix would be to simply disable the labels when in stacked mode.

**Comment by ramugr8** [comment]
Thank you!
We need to show values on stacked bar, is there any other options.

**Comment by mistercrunch** [comment]
Not at the moment no

**Comment by ramugr8** [comment]
Thank you! 
Also i need another help, hope you can solve.
Could you please guide me how to fix colors for legend/charts.

**Comment by mistercrunch** [comment]
fixed in master

**Comment by Stevie337** [comment]
Has the issue been resolved since opening? I still see that stacked bar values are not dynamic. 

Would it also be possible to list the values of the breakdowns as well? 

![image](https://user-images.githubusercontent.com/35451371/34944392-a910976c-f9ff-11e7-9e61-3bcdd2144f6c.png)

![image](https://user-images.githubusercontent.com/35451371/34944415-c221caa0-f9ff-11e7-8ec9-28dbaf104fa5.png)

**Comment by amine5822003** [comment]
Hi,

Is there a way to correct this ? Since the computation exist (when editing or filtering you can go from stacked to grouped with labels correctly displayed), this should only be a refresh issue.

Cheers

**Comment by wenchma** [comment]
any idea for stacked bar values not changing with the filtering ?

**Comment by wenchma** [comment]
@mistercrunch  which commit to fix this issue?
