### ISSUE TITLE
`explore_json` returns ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by xianping** [airbnb/superset#2788]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset (0.17.5)

### Expected results
wish valid data returned.

### Actual results
“network error"

### Steps to reproduce

using 'group by' only works for 'table view', don't work for others viz, like 'Time series- Line chart'.
"network error" display. Inspect in chrome says 'no data return' from server. 
(my dt format is like '2017-05-01' which is 'DATE' type)
The SQL query below:
```
SELECT platform_type AS platform_type,
       DATE(dt) AS __timestamp,
       session_count_10_mins / session_count_all AS `SSR - Watch Length > 10 Minutes`
FROM ssr_daily
INNER JOIN
  (SELECT platform_type AS platform_type__,
          session_count_10_mins / session_count_all AS mme_inner__
   FROM ssr_daily
   WHERE dt >= STR_TO_DATE('2017-04-22 04:20:24', '%%Y-%%m-%%d %%H:%%i:%%s')
     AND dt <= STR_TO_DATE('2017-05-20 04:20:24', '%%Y-%%m-%%d %%H:%%i:%%s')
   GROUP BY platform_type
   ORDER BY mme_inner__ DESC
   LIMIT 50) AS anon_1 ON platform_type = platform_type__
WHERE dt >= STR_TO_DATE('2017-04-22 04:20:24', '%%Y-%%m-%%d %%H:%%i:%%s')
  AND dt <= STR_TO_DATE('2017-05-20 04:20:24', '%%Y-%%m-%%d %%H:%%i:%%s')
GROUP BY platform_type,
         DATE(dt)
ORDER BY `SSR - Watch Length > 10 Minutes` DESC
LIMIT 5000
```

![image](https://cloud.githubusercontent.com/assets/3961545/26275380/b556122a-3d91-11e7-93ed-5add05a55d49.png)

**Comment by mistercrunch** [comment]
Network error = web server timeout, in the latest version we provide a more actionable timeout message.

**Comment by xianping** [comment]
where to setup the timeout configuration?

**Comment by xianping** [comment]
I don't trust timeout issue. 'Network error' returns in 3 seconds. I check the code in config.py, SUPERSET_WEBSERVER_TIMEOUT=60(SECOND?). 
Please help more.
attach inspect info in chrome network:
![image](https://cloud.githubusercontent.com/assets/3961545/26297694/902e575c-3f06-11e7-8d7f-a90c537e7292.png)

**Comment by xrmx** [comment]
@xianping googling it looks like it's something wrong in the client and the internet suggests to clean cookies.

**Comment by xianping** [comment]
thanks @xrmx, I tested to clean cookies, still encounter same problem.
It seems there are issues in Javascript. See attachment when loading the page.
![image](https://cloud.githubusercontent.com/assets/3961545/26300048/8f0990ae-3f0f-11e7-8f4e-e3afff6b5026.png)

**Comment by xrmx** [comment]
@xianping Update to a newer release then, should be fixed.

**Comment by xianping** [comment]
@xrmx , which version do you suggest? I recently installed by using pip which shows up 0.17.5. Should I install by using source code or still can use pip (how to upgrade?)?

**Comment by xianping** [comment]
@xrmx ,i update to 0.18.2 which is latest in pip. The problem is still there, are you sure new version has fixed the issue?

**Comment by xianping** [comment]
@mistercrunch ,could you reopen this issue?

**Comment by mistercrunch** [comment]
How do I reproduce this error?

**Comment by xianping** [comment]
@mistercrunch , can you call successfully with 'groupby' by using 'Line chart'? You can make up any data in table by using 'group by ' call for 'line chart', I think you can reproduce it. 
attach my data example snippet.
`dt, type1, type2, cnt1,cnt2,cnt3,cnt4
'2017-04-23','foo','mobile','219033','126552','116143','107536'
'2017-04-23','foo','pc','53275','37074','35112','34014'
'2017-04-23','bar','mobile','204764','117486','107805','97250'
'2017-04-23','bar','pc','16763','352219','33350','31374'
'2017-04-24','foo','mobile','285522','134723','124730','114265'
'2017-04-24','foo','pc','566305','3419','38200','36346'
'2017-04-24','bar','mobile','211021','122358','114468','102454'
'2017-04-24','bar','pc','5422','38321','36572','37781'
`

**Comment by mistercrunch** [comment]
There are over 1000 Superset users at Airbnb, if groupby in line chart was broken we would know about it.

What database backend are you using? Do you get any stack trace on the web server?

**Comment by xianping** [comment]
@mistercrunch, I am using mysql backend. I don't see any error message in webserver, only the SQL sentence print out.

**Comment by mistercrunch** [comment]
Can't reproduce. Try with latest version. I remember some errors used to be silenced without any logging and that shouldn't be the case in the latest version.

Does this problem occur on the examples we ship with?

You either have to debug on your own or to find a way for us to reproduce this.

**Comment by xianping** [comment]
We fix this by eliminating all metadata in DB and reinstall. I though it's because the displayed mysql table has been modified to extend columns. I don't know what teammates do to reimport table, metadata tables may stay inconsistent.  
If I can reproduce this , let you know.
Thanks all of you.
